dist: trusty
sudo: true

language: node_js

node_js:
  - "8.9"

cache:
  yarn: true
  directories:
     - node_modules

before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn


install:
  - yarn

script:
  - yarn build

notifications:
  email: false
